#
# Build PxTask
#

SET(PXSHARED_SOURCE_DIR ${PROJECT_SOURCE_DIR}/../../../../src)

SET(LL_SOURCE_DIR ${PXSHARED_SOURCE_DIR}/task)

SET(PXTASK_PLATFORM_INCLUDES
	$ENV{EMSCRIPTEN}/system/include
)

SET(PXTASK_COMPILE_DEFS 
	${PXSHARED_HTML5_COMPILE_DEFS};PX_FOUNDATION_DLL=0;
	$<$<CONFIG:debug>:${PXSHARED_HTML5_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PXSHARED_HTML5_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PXSHARED_HTML5_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PXSHARED_HTML5_RELEASE_COMPILE_DEFS};>
)

# include PxTask common
INCLUDE(../common/PxTask.cmake)
