#
# Build PxTask
#

SET(PXSHARED_SOURCE_DIR ${PROJECT_SOURCE_DIR}/../../../../src)

SET(PXTASK_COMPILE_DEFS 
	${PXSHARED_WINDOWS_COMPILE_DEFS};_LIB
	
	$<$<CONFIG:debug>:${PXSHARED_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PXSHARED_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PXSHARED_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PXSHARED_WINDOWS_RELEASE_COMPILE_DEFS};>
)

SET(PXTASK_LIBTYPE STATIC)

# include PxTask common
INCLUDE(../common/PxTask.cmake)
