#
# Build PsFastXml common
#

SET(PSFASTXML_HEADERS
	${LL_SOURCE_DIR}/include/PsFastXml.h
)
SOURCE_GROUP(include FILES ${PSFASTXML_HEADERS})

SET(PSFASTXML_SOURCE
	${LL_SOURCE_DIR}/src/PsFastXml.cpp
)
SOURCE_GROUP(src FILES ${PSFASTXML_SOURCE})

ADD_LIBRARY(PsFastXml STATIC 	
	${PSFASTXML_HEADERS}
	${PSFASTXML_SOURCE}
)

TARGET_INCLUDE_DIRECTORIES(PsFastXml 
	PRIVATE ${PXSHARED_SOURCE_DIR}/../include
	PRIVATE ${PXSHARED_SOURCE_DIR}/foundation/include
	PRIVATE ${LL_SOURCE_DIR}/include
	
	PRIVATE ${PLATFORM_INCLUDES}
)

TARGET_COMPILE_DEFINITIONS(PsFastXml 
	PRIVATE ${PSFASTXML_COMPILE_DEFS}
)

SET_TARGET_PROPERTIES(PsFastXml PROPERTIES 
	COMPILE_PDB_NAME_DEBUG "PsFastXml${CMAKE_DEBUG_POSTFIX}"
	COMPILE_PDB_NAME_CHECKED "PsFastXml${CMAKE_CHECKED_POSTFIX}"
	COMPILE_PDB_NAME_PROFILE "PsFastXml${CMAKE_PROFILE_POSTFIX}"
	COMPILE_PDB_NAME_RELEASE "PsFastXml${CMAKE_RELEASE_POSTFIX}"
)